#
## Build pipeline
#

trigger:
  branches:
    include:
    - master
    - SolidCI/*
 
pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'
  projectFolder: '$(Build.SourcesDirectory)'
  solidCIPowershellFolder: $(projectFolder)/SolidCI.Azure/Content/Powershell
  FEED_ID: "Configured@NugetPrepareStep"

steps:

#
# use the installer tool to setup the nuget exe path.
#
- task: NuGetToolInstaller@0
  displayName: Nuget - install

#
# Restore nuget packages
#
- task: DotNetCoreCLI@2
  displayName: Nuget - restore
  inputs:
    command: restore
    projects: '$(projectFolder)/**/*.csproj'
    feedsToUse: config
    nugetConfigPath: $(projectFolder)/nuget.config

#
# Prepare nuget packages
#
- task: PowerShell@2
  displayName: SolidCI - Nuget prepare
  inputs:
    targetType: "filePath"
    filePath: $(solidCIPowershellFolder)/AzurePipelineScripts/solidci-nuget-prepare.ps1
  env: 
    projectFolder: $(projectFolder)
    nugetConfigPath: $(projectFolder)/nuget.config
        
#
# Build stuff
#
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'Build - dotnet build $(buildConfiguration)'
  workingDirectory: $(projectFolder)

#
# Run tests
#
- task: DotNetCoreCLI@2
  displayName: Test - Run test projects
  inputs:
    command: test
    projects: '$(projectFolder)/**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'


#
# Pack it in a nuget assembly and copy to artifacts folder, then push it
#
- script: dotnet pack
  displayName: 'Nuget - Create packages'
  workingDirectory: $(projectFolder)

- task: CopyFiles@2
  displayName: 'Nuget - Copy packages to staging folder'
  inputs:
    contents: '$(projectFolder)/**/*.nupkg'
    targetFolder: $(Build.ArtifactStagingDirectory)

- task: NuGetCommand@2
  displayName: 'Nuget - push'
  inputs:
    command: push
    publishVstsFeed: $(FEED_ID)

